"""Register discovery candidates; metadata is not a full-text assessment."""
import csv,json
from pathlib import Path
BASE=Path(__file__).resolve().parents[1]; E=BASE/'evidence'
entries=[];routes=[]
def add(sid,title,author,year,kind,publisher,url,themes,scope='landing_page',more=(),doi='',peer='niet vastgesteld'):
 entries.append(dict(id=sid,titel=title,auteur=author,jaar=year,type=kind,publisher=publisher,doi_url=doi or url,peer_reviewed=peer,primair_secundair='te classificeren per gebruik',onderzoeksdoel='nog niet geëxtraheerd',methode='nog niet geëxtraheerd',relevante_definities='nog niet geëxtraheerd',belangrijkste_bevindingen='nog niet geëxtraheerd',beperkingen='Ontdekkingsmetadata; volledige tekst en publicatieversie nog te beoordelen.',relevantie_mdm=themes,themas=themes,citatie=f'{author} ({year}). {title}. {publisher}. {doi or url}',selectiestatus='kandidaat; inhoudelijke screening nog uit te voeren',metadata_bron=url))
 cat='books' if 'boek' in kind else 'methods' if kind=='reviewmethodologie' else 'professional' if kind=='leveranciersboek' else 'standards' if kind=='standaardinformatie' else 'papers'
 if kind=='leveranciersboek':cat='professional'
 for u,sc in [(url,scope),*more]:routes.append(dict(source_id=sid,url=u,category=cat,document_scope=sc,discovered_from='web discovery 2026-09-08; primary landing page: '+url))
add('B01','Master Data Management','David Loshin','2008','boek','Morgan Kaufmann / Elsevier','https://shop.elsevier.com/books/master-data-management/loshin/978-0-12-374225-4','MDM;capabilities;governance;quality',more=[('https://booksite.elsevier.com/samplechapters/9780123742254/Sample_Chapters/02~Chapter_1.pdf','publisher_sample_chapter')],peer='niet vastgesteld; professioneel boek')
add('B02','Enterprise Master Data Management: An SOA Approach to Managing Core Information','Allen Dreibelbis; Eberhard Hechler; Ivan Milman; Martin Oberhofer; Paul van Run; Dan Wolfson','2008','boek','IBM Press / Pearson','https://www.informit.com/store/enterprise-master-data-management-an-soa-approach-to-9780132799720','MDM;architecture;capabilities;governance',more=[('https://ptgmedia.pearsoncmg.com/images/9780132366250/samplepages/0132366258_Sample.pdf','publisher_sample')])
add('B03','Master Data Management and Data Governance, 2/E','Alex Berson; Larry Dubov','2011 (copyright); 2010 (publicatie)','boek','McGraw Hill','https://www.mheducation.com/highered/mhp/product/master-data-management-data-governance-2-e.html','MDM;governance;architecture')
add('B04','Data Matching: Concepts and Techniques for Record Linkage, Entity Resolution, and Duplicate Detection','Peter Christen','2012','boek','Springer','https://link.springer.com/book/10.1007/978-3-642-31164-2','entity resolution;matching;deduplication',doi='https://doi.org/10.1007/978-3-642-31164-2')
add('B05','Data Quality: Concepts, Methodologies and Techniques','Carlo Batini; Monica Scannapieco','2006','boek','Springer','https://link.springer.com/book/10.1007/3-540-33173-5','quality;identity;data integration',doi='https://doi.org/10.1007/3-540-33173-5')
add('B06','An Introduction to Ontology Engineering','C. Maria Keet','2020 (open versie 1.5)','open leerboek','Auteur / University of Cape Town','https://people.cs.uct.ac.za/~mkeet/OEbook/','ontology;conceptual modelling;knowledge representation',more=[('https://people.cs.uct.ac.za/~mkeet/files/OEbook.pdf','open_textbook_2020_not_latest_commercial_edition')])
add('B07','Knowledge Graphs','Aidan Hogan; Eva Blomqvist; Michael Cochez; Claudia d’Amato; Gerard de Melo; Claudio Gutierrez; Sabrina Kirrane; José Emilio Labra Gayo; Roberto Navigli; Sebastian Neumaier; Axel-Cyrille Ngonga Ngomo; Axel Polleres; Sabbir M. Rashid; Anisa Rula; Lukas Schmelzeisen; Juan Sequeda; Steffen Staab; Antoine Zimmermann','2021','boek','Springer; oorspronkelijk Morgan & Claypool','https://kgbook.org/','knowledge graphs;semantics;quality;provenance',scope='author_hosted_full_html_book',doi='https://doi.org/10.2200/S01125ED1V01Y202109DSK022')
add('B08','Data Mesh: Delivering Data-Driven Value at Scale','Zhamak Dehghani','2022','boek','O’Reilly','https://www.oreilly.com/library/view/data-mesh/9781492092384/titlepage01.html','data mesh;data products;federated governance',more=[('https://www.thoughtworks.com/content/dam/thoughtworks/documents/books/bk_data_mesh_excerpt.pdf','authorized_book_excerpt')])
add('P01','Smarter Modeling of IBM InfoSphere Master Data Management Solutions','Jan-Bernd Bracht; Joerg Rehr; Markus Siebert; Rouven Thimm','2012','leveranciersboek','IBM Redbooks','https://www.redbooks.ibm.com/abstracts/sg247956.html','MDM;modelling;architecture',more=[('https://www.redbooks.ibm.com/redbooks/pdfs/sg247956.pdf','public_vendor_book')],peer='nee; leveranciersliteratuur')
add('P02','Master Data Management for SaaS Applications','Whei-Jen Chen; Bhavani Eshwar; Ramya Rajendiran; Shettigar Srinivas; Manjunath B Subramanian; Bharathi Venkatasubramanian','2014','leveranciersboek','IBM Redbooks','https://www.redbooks.ibm.com/abstracts/sg248220.html','MDM;cloud;distribution;integration',more=[('https://www.redbooks.ibm.com/redbooks/pdfs/sg248220.pdf','public_vendor_book')],peer='nee; leveranciersliteratuur')
add('L20','Strategic Business Requirements for Master Data Management Systems','Boris Otto; Martin H. Ofner','2011','conferentiepublicatie','AIS / AMCIS','https://aisel.aisnet.org/amcis2011_submissions/108/','MDM;capabilities;business requirements',peer='conferentiepublicatie; reviewstatus nog afzonderlijk controleren')
add('L21','Entity Resolution: Theory, Practice & Open Challenges','Lise Getoor; Ashwin Machanavajjhala','2012','conferentietutorial','PVLDB','https://vldb.org/pvldb/vol5/p2018_lisegetoor_vldb2012.pdf','entity resolution;matching;identity',scope='proceedings_tutorial_pdf')
add('L22','Evaluating Entity Resolution Results','','2010','conferentiepublicatie','PVLDB','https://www.vldb.org/pvldb/vol3/R18.pdf','entity resolution;evaluation;quality',scope='proceedings_pdf')
add('L23','Data Mesh: a Systematic Gray Literature Review','Abel Goedegebuure; Indika Kumara; Stefan Driessen; Dario Di Nucci; Geert Monsieur; Willem-Jan van den Heuvel; Damian Andrew Tamburri','2023 (preprint)','preprint','arXiv','https://arxiv.org/abs/2304.01062','data mesh;governance;capabilities',more=[('https://arxiv.org/pdf/2304.01062','preprint_full_text'),('https://stefan-driessen.github.io/publication/data-mesh-systematic-grey-literature-study/Data%20Mesh%20-%20Systematic%20Grey%20Literature%20Study.pdf','author_manuscript_not_final_version')],peer='nee voor geregistreerde preprint; latere tijdschriftversie afzonderlijk controleren')
add('L24','The Future of Data Management: A Delimitation of Data Platforms, Data Spaces, Data Meshes, and Data Fabrics','','2025','tijdschriftartikel','Springer','https://link.springer.com/article/10.1007/s10257-025-00707-4','data mesh;data fabric;federation;architecture',doi='https://doi.org/10.1007/s10257-025-00707-4')
add('L25','Data catalog tools: A systematic multivocal literature review','','2025','tijdschriftartikel','Elsevier / Journal of Systems and Software','https://www.sciencedirect.com/science/article/pii/S0164121225002535','metadata;catalog;capabilities;data products',doi='https://doi.org/10.1016/j.jss.2025.112584')
add('L26','Mapping the evolution of data governance scientific research','H. Hassani; X. Huang; S. MacFeely','2025','tijdschriftartikel','Cambridge / Data & Policy; IIASA repository','https://pure.iiasa.ac.at/id/eprint/20795/','governance;research landscape',doi='https://doi.org/10.1017/dap.2025.10014')
add('L27','Impact of a Master Data Management Framework to Trigger Data Governance Maturity: A Systematic Literature Review','','2025','tijdschriftartikel','IEEE Access','https://doi.org/10.1109/ACCESS.2025.3627855','MDM;governance;maturity;review')
add('L28','From Compliance to Value: Data Governance Implementation Challenges to Turn Data into a Strategic Asset—A Systematic Literature Review','Ignacio Acuña; Ania Cravero; Marta Zorrilla','2026','tijdschriftartikel','MDPI / Applied Sciences','https://www.mdpi.com/2076-3417/16/11/5289','governance;implementation;review',more=[('https://www.mdpi.com/2076-3417/16/11/5289/pdf','publisher_pdf_candidate')],doi='https://doi.org/10.3390/app16115289')
add('L29','End-to-End Entity Resolution for Big Data: A Survey','','2019 (preprint)','preprint','arXiv','https://arxiv.org/abs/1905.06397','entity resolution;matching;deduplication',more=[('https://arxiv.org/pdf/1905.06397','preprint_full_text')],peer='nee voor geregistreerde preprint')
add('L30','A Survey of Blocking and Filtering Techniques for Entity Resolution','','2019 (preprint)','preprint','arXiv','https://arxiv.org/abs/1905.06167','entity resolution;blocking;scalability',more=[('https://arxiv.org/pdf/1905.06167','preprint_full_text')],peer='nee voor geregistreerde preprint')
add('L31','xLP: Explainable Link Prediction for Master Data Management','Balaji Ganesan; Matheen Ahmed Pasha; Srinivasa Parkala; Neeraj R Singh; Gayatri Mishra; Sumit Bhatia; Hima Patel; Somashekar Naganna; Sameep Mehta','2024 (preprint)','preprint','arXiv','https://arxiv.org/abs/2403.09806','MDM;AI;explainability;entity resolution',more=[('https://arxiv.org/pdf/2403.09806','preprint_full_text')],peer='nee voor geregistreerde preprint')
add('M01','PRISMA Extension for Scoping Reviews (PRISMA-ScR): Checklist and Explanation','','2018','reviewmethodologie','Annals of Internal Medicine; auteursmanuscript White Rose','https://eprints.whiterose.ac.uk/136633/1/PRISMA_ScR_Manuscript_July6th_clean_1_.pdf','scoping review;reporting',scope='repository_author_manuscript',doi='https://doi.org/10.7326/M18-0850')
add('M02','PRISMA-S: an extension to the PRISMA statement for reporting literature searches in systematic reviews','','2021','reviewmethodologie','Systematic Reviews; PMC','https://pmc.ncbi.nlm.nih.gov/articles/PMC8270366/','search strategy;reproducibility')
add('S52','ISO 8601 — Date and time format','ISO','','standaardinformatie','ISO','https://www.iso.org/iso-8601-date-and-time-format.html','temporality;date representation',scope='official_series_overview_not_full_norm')
add('B09','Data Governance: How to Design, Deploy, and Sustain an Effective Data Governance Program','John Ladley','2019','boek','Academic Press / Elsevier','https://shop.elsevier.com/books/data-governance/ladley/978-0-12-815831-9','governance;stewardship;capabilities')
# Additional routes for already registered works preserve original IDs.
for sid,u,sc in [('L08','https://www.inf.ufes.br/~gguizzardi/OFSCM.pdf','author_hosted_thesis'),('L27','https://repositorioaberto.uab.pt/bitstreams/12897f32-bf0e-446e-ae94-2e6bc2a78ac7/download','institutional_repository_paper'),('L01','https://aisel.aisnet.org/cgi/viewcontent.cgi?article=2693&context=misq','venue_download'),('L20','https://aisel.aisnet.org/cgi/viewcontent.cgi?article=1134&context=amcis2011_submissions','venue_download'),('S01','https://dama.org/learning-resources/dama-data-management-body-of-knowledge-dmbok/','official_overview_not_book'),('S01','https://dama.org/dmbok2r-infographics/','official_open_figures_landing_page_not_book'),('L13','https://arxiv.org/pdf/2003.02320','author_preprint'),('L16','https://proceedings.neurips.cc/paper_files/paper/2020/file/6b493230205f780e1bc26945df7481e5-Paper.pdf','proceedings_full_paper')]:
 routes.append(dict(source_id=sid,url=u,category='standards' if sid.startswith('S') else 'papers',document_scope=sc,discovered_from='primary venue or author repository of registered work'))
for name,data in [('new-source-candidates.csv',entries),('download-seeds.csv',routes)]:
 with (E/name).open('w',encoding='utf-8-sig',newline='') as f:
  w=csv.DictWriter(f,fieldnames=list(data[0]));w.writeheader();w.writerows(data)
print(len(entries),'new candidates;',len(routes),'download routes')
