from pathlib import Path
ROOT=Path(__file__).resolve().parent.parent

def edit(n,fn):
 p=ROOT/n;p.write_text(fn(p.read_text()))

def replacepart(s,start,end,new):
 a=s.index(start);b=s.index(end,a);return s[:a]+new+'\n\n'+s[b:]
edit('paper.tex',lambda s:s.replace('Een ontwerpgerichte integratie van standaarden, semantische verantwoordelijkheden en toetsbare ontwerpprincipes','Een pre-evaluation design proposal over contextbinding en toetsbare meerwaarde').replace('50 standaard- en kadervermeldingen en 17 literatuurvermeldingen','51 standaard- en kadervermeldingen en 19 literatuurvermeldingen, inclusief drie tijdens de kritische review toegevoegde antecedenten').replace('De beoogde bijdrage is een expliciete bewijs- en afhankelijkhedengraaf tussen rechtsgrond, begrip, ontologie, informatiemodel, data-element, record en dataproduct.','De kandidaatbijdrage is een toetsbaar contextbindingsprofiel voor uitspraken over identiteit, tijd en gezag, met een conventioneel contextregister als concurrerende verklaring. Semantische masterdata en productontologieën zijn reeds bestaand werk.').replace('\\input{sections/discussion}','\\input{sections/discussion}\n\\input{sections/pre-evaluation}').replace('S01--S50 en L01--L17','S01--S51 en L01--L19').replace('De peildatum is 7 september 2026. Zij verwijst naar de eerdere bronraadpleging in het dossier, niet naar een nieuwe verificatie tijdens het schrijven.','De peildatum is 7 september 2026. Het oorspronkelijke dossier is tijdens een gerichte kritische review aangevuld met S51, L18 en L19. De broncontrole onderscheidt opnieuw gelezen passages, bibliografische bevestiging en onvolledige toegang.').replace('Het manuscript is geen actualiteitsmonitor.','De nieuwe controle staat in \\texttt{source-audit.csv}; het manuscript is geen volledige actualiteitsmonitor.').replace('\\bibliographystyle{plainnat}','\\section{Uitgebreide standaardvergelijking}\n\\label{sec:full-standards}\n\\input{sections/cross-standard-table}\n\\bibliographystyle{plainnat}'))
p=ROOT/'sections/context-analysis.tex';s=p.read_text();a=s.index('\\begingroup\\small');b=s.index('\\endgroup',a)+len('\\endgroup');(ROOT/'sections/cross-standard-table.tex').write_text(s[a:b]);s=s[:a]+'De uitgebreide functionele vergelijking staat in bijlage~\\ref{sec:full-standards}. De hoofdtekst concentreert zich hieronder op de beslissingen die niet door één standaard worden opgelost.\n'+s[b:];p.write_text(s)
p=ROOT/'sections/introduction.tex';s=p.read_text();s=replacepart(s,'\\subsection{Wetenschappelijke knowledge gap}','\\subsection{Maatschappelijke en wetenschappelijke relevantie}',r'''\subsection{Wetenschappelijke kennisvraag en antecedenten}
De brede claim dat masterdata nog niet met semantische technologie worden verbonden, is niet houdbaar. Wang et al. beschrijven al in 2009 SMDM met virtuele RDF-toegang, ontologieën en mappings. \citep{L18} DPROD biedt productmetadata en Gualo et al. operationaliseren masterdatakwaliteit. \citep{S51,L19} Deze tijdens de gerichte tegencontrole gevonden antecedenten maken semantische MDM, productbeschrijving en kwaliteitsmeting op zichzelf ongeschikt als nieuwheidsclaim.

De resterende kennisvraag luidt: wanneer levert expliciete, versiegebonden contextbinding van identiteit, tijd en gezagsgrond bij overheidsgegevens meer interpretatieve en beheermatige waarde dan dezelfde broninhoud in een eenvoudiger conventioneel contextregister? Het gaat om een vergelijkende en conditionele effectvraag. Het corpus toont niet aan dat het voorgestelde antwoord nog nergens bestaat. Een volledige review van verwante oplossingen blijft nodig; het praktische integratieprobleem mag niet worden verward met een bewezen wetenschappelijke lacune.

\begin{longtable}{@{}P{.22\linewidth}P{.32\linewidth}P{.38\linewidth}@{}}
\caption{Antecedenten en resterende vergelijkingsvraag; niet-vermelding van een functie is geen bewijs van afwezigheid.}\\
\toprule Antecedent & Bestaande bijdrage & Wat voor deze paper nog moet worden vastgesteld \\ \midrule
SMDM \citep{L18} & Semantische toegang tot masterdata en koppeling met ontologieën. & Of extra contextbinding bij tijd/gezag boven een bestaande semantische MDM-benadering nodig en nuttig is. \\
MDQM \citep{L05}; kwaliteitsmodel \citep{L19} & Organisatorische/systeemondersteuning en masterdatakwaliteitsmetingen. & Welke consumentuitkomsten boven correct kwaliteitsbeheer veranderen. \\
DPROD \citep{S51} & Productbeschrijving met doel, eigenaar, lifecycle en verbindingen met datasets/diensten. & Welk minimaal aanvullend profiel nodig is voor de gekozen uitspraakcontext; geen generiek productschema opnieuw uitvinden. \\
Governance/kennisgrafen \citep{L07,L13} & Bestaande governanceconcepten en technieken voor context en verwerking. & Welke combinatie meerwaarde heeft bij expliciet gemeten kosten en rivaliserende implementaties. \\
\bottomrule\end{longtable}

De kandidaatbijdrage is dus geen nieuwe opslagtechniek of universele ontologie. Zij bestaat uit een expliciet contextbindingscontract, afgebakende mechanismen en een experiment dat ook een eenvoudiger ontwerp kan laten winnen. In termen van DSR blijft nog te bepalen of dit verbetering, contextuele toepassing of routineontwerp is. \citep{L04}''')
s=s.replace('Het doel is een onderbouwd ontwerpvoorstel te formuleren voor de samenhang tussen bestaande standaarden, met expliciete aannames, grenzen en een uitvoerbaar evaluatieplan.','Het doel is een onderbouwd, falsifieerbaar ontwerpvoorstel te formuleren. De centrale these T luidt: bij taken die identiteit, tijd en gezag combineren, kan expliciete contextbinding netto meerwaarde bieden boven dezelfde informatie in een conventioneel register. Noodzaak van RDF, centrale opslag, alle vijftien voorzieningen of OntoUML maakt geen deel uit van T.')
s=s.replace('Het onderzoek gebruikt uitsluitend \\texttt{research-design.md}, \\texttt{standards-matrix.csv}, \\texttt{literature-matrix.csv}, \\texttt{claims-register.csv} en de daarin vastgelegde bronnen en bronbeperkingen. Het dossier omvat 50 vermeldingen van standaarden, specificaties, vocabularia, methoden en kaders, plus 17 literatuurvermeldingen. Dit zijn geen 67 onafhankelijke studies.','Het onderzoek vertrok uit het repositorydossier met 50 standaard-/kadervermeldingen en 17 literatuurvermeldingen. Een afzonderlijk vastgelegde kritische review voegde één productontologie en twee academische antecedenten toe, vóór herziening van de argumentatie: S51, L18 en L19. De herziene matrices bevatten 51 respectievelijk 19 vermeldingen; dit zijn geen 70 onafhankelijke studies. De zoekstrings en selectie zijn vastgelegd in \\texttt{review/search-log.md}.')
s=s.replace('Deze toevoegingen introduceren geen nieuwe externe bewijsbronnen.','De latere review introduceert drie expliciet geregistreerde externe antecedenten en TP1--TP4 als niet-getoetste propositions. Zij is door dezelfde AI-assistent uitgevoerd, niet door een organisatorisch onafhankelijke reviewer. Het oorspronkelijke manuscript en de volledige review zijn vóór de revisie bewaard.')
s=s.replace('De oorspronkelijke R01--R22 en hun bronkoppelingen blijven behouden.','De identifiers R01--R23 blijven behouden. Een afzonderlijk \\texttt{derivation-register.csv} maakt aanvullende aannames, alternatieven en experimentkoppelingen expliciet.')
s+=r'''
\subsection{Afleiding en DSR-beslismomenten}
De afleiding onderscheidt vier beweringstypen: een bron beschrijft een constructie; een norm stelt binnen scope een eis; de ontwerper kiest een aanvullende contractregel; een hypothese voorspelt een effect. De overgang van de eerste twee naar de laatste twee vereist een expliciete aanname. Een beschikbare provenanceproperty bijvoorbeeld maakt context representabel, maar verplicht geen uitspraakgebonden register en voorspelt geen betere antwoorden. \citep{S33}

DSR wordt gebruikt als onderzoeksorganisatie, niet als kwaliteitsstempel. De uitgevoerde activiteiten zijn dossieranalyse, brontegencontrole en specificatie van een voorstel. De analytische voorbeelden hieronder zijn geen demonstratie van software. Gate G-A verlangt bron- en constructreview; G-B een bevroren minimale implementatie en geadjudiceerde taakset; G-C een preregistratie van uitkomsten, marges en analyse; G-D uitvoering van vergelijkende en praktijkgerichte evaluatie. Geen van deze gates wordt door compilatie of administratieve traceability vervuld. \citep{L02,L03}
''';p.write_text(s)
p=ROOT/'sections/theory.tex';s=p.read_text();pos=s.index('\\subsection{Metadata en data-elementen}');s=s[:pos]+r'''
\subsubsection{Operationele afbakening en grensgevallen}
Binnen dit onderzoek is een publicatie precies dan een SMDP-kandidaat als zij gezamenlijk aan vier voorwaarden voldoet: (a) zij levert of ontsluit herhaald gebruikte uitspraken over geïdentificeerde domeinentiteiten; (b) een producteigenaar legt gebruiksdoel, versie en verantwoordelijkheden vast; (c) geselecteerde gegevenselementen zijn via getypeerde verwijzingen verbonden met hun interpretatiecontext; en (d) het contract beschrijft hoe afnemers bron-, tijd-, gezags- en ontbrekende-bewijsinformatie kunnen verkrijgen. Dit zijn noodzakelijke en gezamenlijk voldoende voorwaarden voor de \emph{onderzoekscategorie}, niet voor kwaliteit, normconformiteit of bewezen nut. Een concrete toepassing kan eraan voldoen en toch de centrale these weerleggen.

Een begrippenregister zonder aangeboden mastergegevens voldoet niet aan (a). Een dataset met alleen een technische schema-URL voldoet niet vanzelf aan (c). Een volledig gedocumenteerd conventioneel register kan wel voldoen: het begrip schrijft geen graafdatabase voor. Het experiment moet daarom de mate en vorm van contextbinding manipuleren in plaats van simpelweg producten met en zonder het label SMDP te vergelijken.

Masterdata, referentiedata en metadata zijn gebruiksrollen. Een beheerde waardenlijst classificeert in de referentierol, terwijl de beschrijving van die lijst metadata is. De organisatie die een product bezit kan zelf onderwerp van masterdata zijn; haar vermelding als eigenaar is productmetadata. Een gebeurtenisrecord is niet louter door hergebruik masterdata. Dataset, dienst en product beschrijven publicatie-/gebruiksobjecten en behoren niet tot dezelfde disjuncte classificatie als inhoudsrollen. Deze operationalisering sluit aan op de onderscheiden registratieniveaus en productoriëntatie, maar is eigen onderzoeksafbakening. \citep{S08,S47,L12,L19}

''' +s[pos:]
s=s.replace('De voorgestelde koppeling van een MIM-attribuut aan een 11179-data-element is daarom een mapping tussen metamodelconstructies, geen vanzelfsprekende identiteit.','De voorgestelde koppeling van een MIM-attribuut aan een 11179-data-element is daarom een mapping tussen metamodelconstructies, geen vanzelfsprekende identiteit. ISO/IEC 11179-31 betreft bovendien niet alleen data-elementen maar ook bijbehorende concepten, domeinen, eenheden en afleidingsregels; het ontwerp introduceert deze niet als nieuwe constructies.')
s=s.replace('Deze instrumenten vullen elkaar aan, maar zijn niet onderling verwisselbaar.','Deze instrumenten vullen elkaar aan, maar zijn niet onderling verwisselbaar. SKOS §3.5.1 laat dezelfde resource als SKOS-concept en OWL-klasse toe. De afzonderlijke beheerrollen in dit ontwerp zijn dus geen universele disjunctheidsclaim. Meervoudige typering is toegestaan als interpretatie en beheer expliciet blijven. \\citep{S31}')
s=s.replace('Een foundational ontology levert algemene onderscheidingen;','Een conceptueel informatiemodel kan zelf semantisch zijn; semantiek is geen exclusief tussenstation vóór ontologie. MIM §1.6 onderscheidt beschouwingsniveaus en formuleert begrip als combinatie van term en definitie. Dit onderzoek beheert de aanduiding, definitie-uitspraak en het bedoelde concept afzonderlijk. Dat is een expliciete operationalisering naast het MIM-woordgebruik, geen stilzwijgend aangenomen equivalentie. \\citep{S13}\n\nEen foundational ontology levert algemene onderscheidingen;')
p.write_text(s)
p=ROOT/'sections/architecture.tex';s=p.read_text().replace('Zij schrijft vijftien logische verantwoordelijkheden voor, geen vijftien afzonderlijke applicaties.','Zij ordent vijftien logische verantwoordelijkheden als analyseviews; niet alle views vereisen een eigen artefact of actieve voorziening in elke toepassing. Ontologische verdieping, events en AI-consumptie zijn conditioneel.')
s=s.replace('De graaf is $G_v=(N,E,\\tau,\\rho)$, met knopen $N$, getypeerde relaties $E\\subseteq N\\times R\\times N$, een typefunctie $\\tau$ en een versie-/contextannotatie $\\rho$.','Het gereviseerde graafmodel is $G_v=(N,L,E,\\tau,\\gamma,\\kappa)$, met resourceknopen $N$, literalwaarden $L$ en afzonderlijk geïdentificeerde beweringen/verbindingen $E$. De typering $\\tau:N\\rightarrow\\mathcal{P}(\\mathcal{T})$ staat meerdere representatierollen toe. De incidentiefunctie $\\gamma:E\\rightarrow N\\times R\\times(N\\cup L)$ geeft inhoud en relatietype; $\\kappa:E\\rightarrow K$ bindt iedere verbinding aan een contextrecord. Twee edges met dezelfde inhoud mogen dus verschillende bronnen, versies en gezagsclaims hebben. Ontbrekende contextwaarden krijgen expliciet de status onbekend; zij verdwijnen niet door samenvoeging van triples.')
s=s.replace('Ook een \\emph{Klasse}-knoop en een \\emph{Concept}-knoop blijven afzonderlijke beschrijvingen, zelfs wanneer ze op hetzelfde domeinonderwerp betrekking hebben.','Een \\emph{Klasse}-rol en een \\emph{Concept}-rol blijven onderscheiden. Zij kunnen in een implementatie afzonderlijke identifiers krijgen, of onder expliciet profielbeleid door dezelfde resource worden gedragen; uit meervoudige typering volgt geen ongedocumenteerde model-equivalentie.')
s=s.replace('b=(s,p,o,\\iota_v,\\iota_r,z,\\pi,\\epsilon)','b=(id_b,s,p,o,\\iota_v,\\iota_r,z,\\pi,\\epsilon)')
s=s.replace('waar $s,p,o$ de inhoud aanduiden,','waar $id_b$ de afzonderlijke beweringsidentiteit is, $s,p,o$ de inhoud aanduiden,')
a=s.index('De epistemische annotatie is:');b=s.index('\\subsection{Voorgestelde invarianten}',a)
s=s[:a]+r'''De epistemische annotatie is als eigen profiel gedefinieerd door:
\[
\epsilon=(k,r_g,m,u,g,e,a),
\]
met uitspraaksoort $k$, registratiehandeling $r_g$, productiemethode $m$, onzekerheidsbeschrijving $u$, gezagsgrond $g$, bewijsstatus $e$ en verantwoordelijke $a$. Registratie en afleiding kunnen samen voorkomen. De methode vermeldt bijvoorbeeld menselijke invoer, een berekeningsregel of een geïdentificeerd AI-model; zij maakt geen kansuitspraak. Een AI-methode is niet per definitie een gekalibreerd probabilistisch model. $u$ kan afwezig, onbekend of methodisch beschreven zijn; een getal krijgt alleen een probabilistische interpretatie als die interpretatie is onderbouwd. $g$ onderscheidt wettelijke authenticiteit van ander gezag. $e$ onderscheidt onbeoordeeld, ondersteund, betwist en ingetrokken bewijs. Deze waarden zijn ontwerpkeuzen, geen PROV-O-enumeraties.

Een contextrecord $K$ bindt daarnaast de bronversie, het perspectiefsysteem en relevante model-/mappingversies. Voor bekende tijdsgrenzen wordt de conventie $[begin,einde)$ gekozen. Een open einde en een onbekende grens zijn afzonderlijke toestanden; onbekend is niet oneindig geldig. Een gedeeltelijk geïnterpreteerde relatie kan daardoor geen tweewaardige waarheidsbeslissing afdwingen. De voorlopige controle levert \emph{voldoet}, \emph{schendt} of \emph{onbepaald}; ontbrekende verplichte metadata is een contractschending, maar de inhoudelijke waarheid van het gegeven kan alsnog onbepaald zijn.

\paragraph{Analytisch tegenvoorbeeld, niet uitgevoerd.}
Neem twee synthetische beweringen $b_1$ en $b_2$ met dezelfde inhoud $(x,p,7)$, maar bron A respectievelijk bron B. Alleen A heeft een beoordeelde gezagsgrond. Dan mogen $id_{b_1}$ en $id_{b_2}$ niet door deduplicatie verdwijnen: gelijkheid van waarde impliceert geen gelijkheid van context. Een latere versie $b_3$ corrigeert A naar waarde 8 met terugwerkende geldigheid. Een bekend-op-vraag vóór de correctieregistratie selecteert de eerdere bronversie; een latere bekend-op-vraag selecteert de correctie voor zover de geldigheidsvraag dat vereist. Deze verwachte uitkomst volgt uit het voorgestelde contract, niet uit een gedraaide prototypequery. Een verdedigbare alternatieve implementatie bewaart dezelfde informatie in relationele bewerings- en contexttabellen.

''' +s[b:]
s=s.replace('Een afgeleid gegeven verwijst naar invoerversies, activiteit en regel- of modelversie.','Een afgeleid gegeven verwijst naar invoerversies, activiteit en regel- of modelversie voor zover beschikbaar; ontbrekende noodzakelijke context wordt expliciet als contractafwijking gepubliceerd.')
p.write_text(s)
p=ROOT/'sections/principles.tex';s=p.read_text().replace('afzonderlijk typeren en hun verbindingen expliciet maken.','als onderscheiden rollen typeren en hun verbindingen expliciet maken. Afzonderlijke fysieke resources zijn niet in alle gevallen vereist.').replace('MOET uitspraaksoort, gezagsgrond, afleidingswijze en bewijsstatus afzonderlijk machineleesbaar maken','MOET uitspraaksoort, registratiehandeling, productiemethode, onzekerheidsbeschrijving, gezagsgrond en bewijsstatus afzonderlijk machineleesbaar maken');p.write_text(s)
p=ROOT/'sections/case-evaluation.tex';s=p.read_text().replace('De representatieve keten wordt als toekomstig uitbreidingsontwerp weergegeven:','De nog niet gevalideerde onderzoeksroute wordt als toekomstig uitbreidingsontwerp weergegeven:').replace('Deze scenario’s zijn ontworpen foutprikkels, geen gerapporteerde gebeurtenissen in de BAG.','Deze scenario’s zijn ontworpen foutprikkels, geen gerapporteerde gebeurtenissen in de BAG. Een Stelselbrede effectclaim is pas toelaatbaar na brongecontroleerde evaluatie van minimaal twee onafhankelijk beheerde registraties met inhoudelijk verschillende identiteits- of tijdscontext. Twee registraties zijn een minimale stage-gate, geen bewijs van representativiteit voor het hele Stelsel.')
p.write_text(s)
print('Core manuscript revised; evaluation, derivation and status sections follow.')
