import csv
from pathlib import Path
ROOT=Path(__file__).resolve().parent.parent

def read(n):
 with (ROOT/n).open(encoding='utf-8-sig',newline='') as f:return list(csv.DictReader(f))
def write(n,rows):
 with (ROOT/n).open('w',encoding='utf-8-sig',newline='') as f:
  w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
s=read('standards-matrix.csv');l=read('literature-matrix.csv');c=read('claims-register.csv')
r=dict.fromkeys(s[0],'');r.update(id='S51',standaard='Data Product Ontology (DPROD)',organisatie_eigenaar='Object Management Group (OMG)',type_document='Ontologie / specificatie',status='OMG Adopted Beta Specification; catalogus vermeldt 1.0 beta; geen Nederlandse lijststatus vastgesteld',versie='1.0 Beta 1; document februari 2025, catalogus adoption januari 2025',toepassingsgebied='Beschrijven van dataproducten en hun datasets/diensten',abstractieniveau='Productmetadata en semantische catalogisering',belangrijkste_concepten='DataProduct; owner; purpose; lifecycleStatus; input/output; DataService; Dataset',relatie_master_data='Niet uitsluitend gericht op masterdata; vergelijking voor productpublicatie',relatie_semantiek='RDF-gebaseerde productbeschrijving',relatie_ontologie='Bestaande ontologie voor productmetadata; geen volledige domeinontologie',relatie_governance='Eigenaar en lifecycle als metadatabouwstenen; geen bewijs van werkend beheer',relatie_ai='Geen geverifieerd SMDP- of AI-effect',overlap_andere_standaarden='DCAT; RDF; SHACL; eigen C12/DP6',geconstateerde_hiaten='Volledige Nederlandse gezags-, tijd- en registratieketen niet vastgesteld; beta-status; geen noodzakelijkheid aangetoond',primaire_bron='https://www.omg.org/spec/DPROD/1.0/Beta1/PDF',bronlocatie='Cover; §1 Scope; §8.1 DataProduct; §8.2 DataService; https://www.omg.org/spec/DPROD/1.0/Beta1/About-DPROD',bewijsniveau='Primaire PDF: geselecteerde secties en primaire catalogus gecontroleerd tijdens review',nederlandse_lijststatus='Niet vastgesteld; niet als Nederlandse verplichting gebruikt',geraadpleegd_op='2026-09-07',claim_id='C-S51')
if not any(x['id']=='S51' for x in s):s.append(r)
newlit=[dict(id='L18',auteur='Xiaoyuan Wang; Xingzhi Sun; Feng Cao; Li Ma; Nick Kanellos; Kang Zhang; Yue Pan; Yong Yu',jaar='2009',titel='SMDM: Enhancing Enterprise-Wide Master Data Management Using Semantic Web Technologies',publicatietype='Conferentiedemonstratiepaper; Proceedings of the VLDB Endowment',onderzoeksvraag='Hoe bestaande MDM semantisch uitbreiden met ontologieën, mappings en queries? (parafrase)',methode='Systeemontwerp en demonstratie; technische queryvergelijking gerapporteerd',belangrijkste_bevinding='Semantische MDM met virtuele RDF-toegang en ontologieën is een bestaand antecedent.',relevantie_paper='Weerlegt brede nieuwheid van semantische masterdata; relevante eenvoudigere architectuurvariant.',beperkingen='Bedrijfscontext en demonstratie; geen bewijs voor Nederlands SMDP of menselijke/AI-interpretatie.',doi_of_stabiele_bron='https://www.vldb.org/pvldb/vol2/vldb09-1011.pdf',bewijsniveau='Primaire proceedings-PDF; abstract en architectuursecties gelezen',bronlocatie='Abstract; §1 Introduction; §2 A Tour of the SMDM System; §3 Demonstration',geraadpleegd_op='2026-09-07',claim_id='C-L18'),dict(id='L19',auteur='Fernando Gualo; Ismael Caballero; Moisés Rodríguez; Mario Piattini',jaar='2023',titel='A Data Quality Model for Master Data Repositories',publicatietype='Tijdschriftartikel; Informatica',onderzoeksvraag='Hoe een kwaliteitsmodel en metingen afstemmen op masterdatarepositories? (parafrase)',methode='Ontwerp van kwaliteitsmodel op basis van internationale standaarden; uitgewerkt meetvoorbeeld',belangrijkste_bevinding='Bestaand werk operationaliseert masterdatakwaliteit met eigenschappen en metingen.',relevantie_paper='Antecedent voor kwaliteit; voorkomt dat eigen M01-M23 als nieuwe kwaliteitsmeettaxonomie worden gepresenteerd.',beperkingen='Geen validatie van dit SMDP, Nederlandse gezagsketens of AI; claims beperkt tot gelezen model- en meetbeschrijving.',doi_of_stabiele_bron='https://doi.org/10.15388/23-INFOR534',bewijsniveau='Primaire uitgeverstekst; model- en meetsecties gecontroleerd tijdens review',bronlocatie='https://journals.sagepub.com/doi/10.15388/23-INFOR534 ; introduction, proposed model, measurement example',geraadpleegd_op='2026-09-07',claim_id='C-L19')]
for r in newlit:
 if not any(x['id']==r['id'] for x in l):l.append(r)
# Additional access routes for existing works are not new theoretical sources.
for r in l:
 if r['id']=='L03':r['bronlocatie']+=' ; review: uitgeversmetadata https://www.tandfonline.com/doi/pdf/10.1057/ejis.2014.36 ; volledige inhoud niet opnieuw gelezen'
 if r['id']=='L09':r['bronlocatie']+=' ; review: https://journals.sagepub.com/doi/10.3233/AO-150157 ; uitgeversrecord geverifieerd, volledige tekst niet opnieuw gelezen'
for r in s:
 if r['id']=='S02':r['status']='Gepubliceerde internationale norm; ISO-catalogus vermeldt bevestiging in 2026'
 if r['id']=='S31':r['geconstateerde_hiaten']+='; §3.5.1 laat concept/klasse-dubbeltypering toe; scheiding is profielkeuze'
 if r['id']=='S13':r['geconstateerde_hiaten']+='; §1.6.1 hanteert begrip als combinatie van term en definitie; expliciet woordgebruikverschil met dit onderzoek'
 if r['id']=='S22':r['be-wijsniveau' if False else 'bewijsniveau']+='; review: lijstveld versie 1.1, specificatielinklabel noemt 1.0; geselecteerde 1.1-publicatie apart gecontroleerd'
# Add source claims and four explicitly untested theoretical propositions.
entries=[('C-L18','Wang et al. (2009) beschrijven reeds Semantic Master Data Management met virtuele RDF-toegang, ontologieën en mappings.','bronbevinding','L18','https://www.vldb.org/pvldb/vol2/vldb09-1011.pdf','Abstract; §1-2','Direct antecedent; geen Nederlands SMDP-effectbewijs.'),('C-L19','Gualo et al. (2023) bieden een bestaand model met eigenschappen en metingen voor masterdatakwaliteit.','bronbevinding','L19','https://doi.org/10.15388/23-INFOR534','Model- en meetsecties','Geen bewijs voor de gehele SMDP-integratie.'),('C-S51','DPROD Beta 1 beschrijft dataproductmetadata; het productcontract is daarom geen onontgonnen standaardisatiegebied.','bronbevinding en interpretatie','S51','https://www.omg.org/spec/DPROD/1.0/Beta1/PDF','Cover; §8.1-8.2','Beta-specificatie; geen Nederlandse verplichting.'),('TP1','Bij voldoende bronkwaliteit kan expliciete contextbinding interpretatiefouten verminderen ten opzichte van dezelfde informatie in een conventioneel contextregister.','te toetsen theoretische propositie','L13;L18;S08;S33','','sections/pre-evaluation.tex','Vervalt bij praktisch gelijkwaardig eenvoudiger alternatief binnen vooraf vastgestelde marges.'),('TP2','Expliciete, betrouwbare epistemische annotatie kan onterechte gezagsopwaardering verminderen; misleidende annotatie kan dit voordeel omkeren.','te toetsen theoretische propositie','S33;S25;L16','','sections/pre-evaluation.tex','Geen universeel AI-effect; toets met correcte en onjuiste annotaties.'),('TP3','Ontologische verdieping levert alleen extra netto nut wanneer identiteit-, rol- of categorieproblemen relevant zijn en detectiewinst de extra inspanning rechtvaardigt.','te toetsen theoretische propositie','L08;L09;L10','','sections/pre-evaluation.tex','Een gelijkwaardig eenvoudiger model kan noodzaak en netto voordeel weerleggen.'),('TP4','Versiegebonden afhankelijkheden kunnen historische reconstructie en wijzigingsimpact verbeteren, maar kunnen bij verouderde mappings of resolutiestoringen meer fouten of kosten veroorzaken.','te toetsen theoretische propositie','L14;S33;S47;S22','','sections/pre-evaluation.tex','Vergelijk met hetzelfde versiearchief zonder gekoppelde afhankelijkheden.')]
for cid,claim,typ,src,url,loc,limit in entries:
 if not any(x['claim_id']==cid for x in c):
  r=dict.fromkeys(c[0],'');r.update(claim_id=cid,claim=claim,claimtype=typ,bron_ids=src,primaire_bron=url,bronlocatie=loc,bewijs_samenvatting=claim,bewijsstatus='Bronpassage geverifieerd; gevolgtrekking begrensd' if cid.startswith('C-') else 'Niet empirisch getoetst',beperking_of_tegenbewijs=limit,latere_toets='E1-E4; zie pre-evaluation research state',geraadpleegd_op='2026-09-07');c.append(r)
for r in c:
 if r['claim_id']=='G01':r.update(claim='Brede nieuwheid van semantische masterdata is niet houdbaar; de resterende kennisvraag betreft vergelijkende meerwaarde van contextbinding in de afgebakende Nederlandse casus.',bron_ids='L18;L19;S51;L04',bewijsstatus='Gecorrigeerde gap-positionering na gerichte tegenzoekactie; geen uitputtend nieuwheidsbewijs')
 if r['claim_id']=='R23':r['claim']='Maak uitspraaksoort, registratiehandeling, productiemethode, onzekerheidsmodel, gezagsgrond en bewijsstatus afzonderlijk machineleesbaar per bewering.'
write('standards-matrix.csv',s);write('literature-matrix.csv',l);write('claims-register.csv',c)
print('Sources:',len(s),len(l),'claims:',len(c))
