from pathlib import Path
import csv,json,hashlib
ROOT=Path(__file__).resolve().parent.parent
# The review is written against the archived manuscript before any revisions.
findings=[
('RV01','CRITICAL','De research gap is niet aangetoond','De corpusgebonden lacune wordt eerlijk begrensd, maar selectiebias blijft de enige grond voor een wetenschappelijke lacune. De gerichte tegenzoekactie vindt Wang et al. (2009), SMDM, dat masterdata met een virtuele RDF-laag, ontologieën en queryverwerking verbindt. DPROD adresseert productbeschrijving. Gualo et al. (2023) adresseert masterdatakwaliteit. Daarmee valt de brede nieuwheidsclaim weg; onbekend is welk restprobleem na deze antecedenten overblijft.','Herformuleer de gap als nog onbeantwoorde vergelijkingsvraag over brongebonden identiteit, tijd en gezagsstatus onder semantische verandering. Maak bestaand werk en resterende onzekerheid expliciet.','geaccepteerd','Een nieuw label of ontbrekende vermelding in een klein dossier bewijst geen nieuwe kennis. Een bewijsbare afwezigheidsclaim blijft buiten bereik.','Probleemstelling; related work; conclusie','L18;L19;S51'),
('RV02','MAJOR','De bijdrage is vooralsnog een integratievoorstel','Vijftien lagen, een tuple en een lijst normen leveren geen aangetoonde verklarende of prescriptieve theorie. De bijdrage kan routine engineering zijn. Er ontbreken een afgebakend mechanisme, toepassingscondities en uitkomsten waaronder dat mechanisme geen waarde toevoegt.','Formuleer vier conditionele propositions rond contextbinding, epistemische signalering, selectieve ontologische verdieping en versie-impact; onderscheid representatiecapaciteit van effect.','geaccepteerd','Integratie kan een DSR-bijdrage worden, maar alleen wanneer de overdraagbare ontwerpkennis en haar grenzen worden getoetst.','Theoretische bijdrage; pre-evaluation research state','L04;L13;L18;S51'),
('RV03','MAJOR','SMDP is onvoldoende discriminerend gedefinieerd','De definitie telt wenselijke eigenschappen op. Vrijwel elke goed beheerde dataset plus catalogus kan eronder vallen. Niet helder is welke noodzakelijke voorwaarden een product tot masterdataproduct maken en welke semantische verplichtingen additioneel zijn.','Definieer een minimaal profiel met noodzakelijke en gezamenlijk voldoende voorwaarden binnen dit onderzoek; geef grensgevallen en leg vast dat een semantisch register zonder masterdata geen SMDP is.','geaccepteerd','Een onderzoeksspecifieke classificatieregel is toegestaan, mits niet gepresenteerd als universele standaarddefinitie.','Theoretisch kader: afbakening SMDP','L05;L12;S08;S47'),
('RV04','MAJOR','Masterdata en referentiedata zijn te summier afgebakend','Entiteit versus record is bruikbaar, maar reference data krijgt slechts één zin. De rollen masterdata, referentiedata en metadata kunnen per context wisselen. Strikte scheiding op representatieniveau mag niet leiden tot een onhoudbare universele disjunctie.','Voeg operationele rolclassificatie toe, inclusief waardenlijst, conceptbeschrijving, transactiedatum en productmanifest als grensgevallen; registreer de rolcontext.','geaccepteerd','De inhoudsrol, granulariteit en het publicatieobject zijn onafhankelijke dimensies.','Theoretisch kader: masterdata en kernbegrippen','L05;L19;S08;S47'),
('RV05','MAJOR','De paper verbergt een echte terminologische spanning','MIM 1.2 §1.6.1 beschrijft begrip als combinatie van term en definitie, terwijl de paper deze afzonderlijk modelleert. SKOS §3.5.1 laat bovendien een resource als SKOS-concept én OWL-klasse toe. De eigen scheiding is niet fout, maar volgt niet als universeel verbod uit deze standaarden.','Bespreek het MIM-woordgebruik en maak representatierollen expliciet; corrigeer de implicatie dat SKOS/OWL noodzakelijk disjunct zijn.','geaccepteerd','Afzonderlijke beheerobjecten zijn een verdedigbare profielkeuze. Toegestane standaardpatronen blijven toegelaten als hun interpretatie traceerbaar is.','Theoretisch kader; cross-standard analysis; DP1; metamodel','S13;S31'),
('RV06','MAJOR','Van scope naar normatieve ontwerpverplichting is een te grote stap','ISO 8000-110 behandelt uitwisselberichten met karakteristieke masterdata. ISO/IEC 11179-31 biedt registratiemetadata. Dat ondersteunt geen algemene plicht voor alle interne productgegevens of een bepaalde RDF-implementatie. De paper vermeldt beperkingen, maar het woord MOET in 23 eisen maskeert de inferentiesprong.','Classificeer iedere afleiding als bronconstraint, conditionele toepassing of eigen ontwerpkeuze; documenteer de aanvullende aanname en het toepasselijkheidsbesluit.','geaccepteerd','Een normcatalogus kan scope ondersteunen; niet een ongelezen clausule of een causaal effect.','Requirements; derivation-register; broncontrole','S03;S08'),
('RV07','MAJOR','Vijftien lagen zijn geen beargumenteerde noodzakelijke architectuur','De lagen volgen vrijwel één-op-één de gevraagde onderwerpen. Functionele dekking is daarmee door constructie gegarandeerd, terwijl minimale realisatie, complexiteit en redundantie onbekend blijven. Ontologie, catalogus en dataproductmetadata kunnen grotendeels bestaande profielen hergebruiken.','Presenteer vijftien verantwoordelijkheden als views; definieer een minimale realisatie en optionele profielen. Vergelijk expliciet met een conventioneel register met dezelfde informatie.','geaccepteerd','Dekking van onderwerpen bewijst geen optimale decompositie of noodzaak van afzonderlijke services.','Reference architecture: alternatiefanalyse en minimaliteit','L13;L18;S51'),
('RV08','MINOR','OntoUML is niet noodzakelijk gemaakt; dat is juist','DP8 is terecht conditioneel. Noodzakelijkheid alsnog afdwingen zou de paper verzwakken. Wel ontbreekt een concreet besliscriterium wanneer de extra analyse zinvol kan zijn.','Behoud OntoUML als optionele analysemethode en voeg een probleemtrigger en stopregel toe; toets tegen dezelfde modelreview zonder foundational ontology.','gedeeltelijk','De suggestie dat OntoUML vereist moet zijn wordt verworpen; het verzoek om de keuze scherper te verantwoorden wordt overgenomen.','DP8; architectuuropties; experiment E3','L08;L09;L10;S41'),
('RV09','MAJOR','Het formele metamodel is onvolledig','E als verzameling triples identificeert geen twee gelijkluidende uitspraken van verschillende bronnen. N bevat geen literalwaarden. De typefunctie specificeert geen meervoudige typen. Context, tijdsintervallen en onvolledige informatie missen domeinen en uitkomstregels. Daardoor is het model nog niet voldoende voor reproduceerbare implementatie.','Geef edges/beweringen eigen identiteit, een incidentiefunctie naar nodes of literals, meervoudige typering, contextrecord en driestatus-validatie; beschrijf een synthetisch tegenvoorbeeld zonder uitvoering.','geaccepteerd','Formele precisie is nodig juist waar conflicten en provenance worden geclaimd; dit blijft een partiële specificatie.','Formeel metamodel en invarianten','S28;S31;S33;L14'),
('RV10','MAJOR','Concrete cross-standard mappings ontbreken','Relatienamen zoals formaliseert en modelleert zijn eigen termen. Er is nog geen adjudiceerbare mappingtabel die aangeeft welke standaardconstructies worden hergebruikt, waar extensions ontstaan en welk verlies optreedt.','Voeg kandidaatmappingtabel toe met richting, constructie, verlies, normatieve status en te beoordelen alternatief; hergebruik DPROD als vergelijking in C12.','geaccepteerd','Een volledige nieuwe mappingstandaard is buiten deze fase; kandidaatregels en expliciete resterende beslissingen zijn wel mogelijk.','Cross-standard analysis; mappingcontract','S08;S13;S31;S33;S47;S51'),
('RV11','CRITICAL','Niet acceptabel als afgeronde DSR-evaluatiestudie','Er is geen empirische evaluatie, externe probleemvalidatie of feitelijke prototype-inventarisatie. De paper claimt dat niet, maar de breedte en vorm kunnen toch de indruk van een voltooide DSR-bijdrage geven. DSR-methodologie noemen vervangt evaluatie niet.','Positioneer expliciet als pre-evaluation design proposal; benoem de uitgevoerde ontwerpactiviteiten en de nog niet uitgevoerde demonstratie/evaluatie.','geaccepteerd','Afwijzing als afgeronde studie is gerechtvaardigd; evaluatieresultaten fabriceren is geen oplossing. Een voorsteltrack heeft andere criteria.','Titel; abstract; onderzoeksmethode; slotstatus','L01;L02;L03;L04'),
('RV12','MAJOR','De design principles zijn nog geen empirisch onderbouwde ontwerpwetten','Broncitaten verklaren waarom onderwerpen relevant zijn, maar waarom juist deze normatieve oplossing optimaal is volgt niet. Sommige principes zijn generieke engineeringpraktijken.','Leg per principe probleem, bronpassage, extra aanname, alternatief, verwacht mechanisme, verliesconditie en toekomstige toets vast.','geaccepteerd','De principes blijven afgeleide kandidaten; hun bestaande status wordt niet achteraf opgewaardeerd.','Design principles; derivation-register; traceability','L04;S08;S33'),
('RV13','MAJOR','A/B identificeert het effect van semantiek niet','Zelfs bij dezelfde feiten krijgt B extra structuur, retrievalhulp, provenance en constraints. Winst kan afkomstig zijn van documentatiekwaliteit, navigatie, meer ontwikkeltijd of een betere interface. Een gecombineerde ablatielijst maakt het pakket nog geen causale toets.','Gebruik A0 technisch, A1 conventioneel contextregister met dezelfde inhoud en B1 getypeerde verbindingen; houd toegang/presentatie waar mogelijk gelijk. Test ontologie en epistemische labels afzonderlijk.','geaccepteerd','A0/B kan pakketwaarde meten; A1/B en gerichte manipulaties zijn nodig voor mechanistische claims.','Evaluatie: condities, variabelen en estimands','L03;L13;L16'),
('RV14','MAJOR','Veel metrics meten naleving van de eigen definitie','Semantic completeness, explainability en traceability dreigen tautologisch te worden: B bevat de velden die de metric telt, A niet. Metadatadekking is bovendien geen juistheid. Mappingrecall vereist een eindige, vooraf bepaalde kandidatenverzameling.','Scheid artefactconformiteit van consumentuitkomsten, definieer gouden standaard en denominatoren, meet fout-positieven, correcte onthouding en kosten apart.','geaccepteerd','Een metadatacontrole blijft nuttig als formatieve toets, maar mag de comparatieve hoofdclaim niet dragen.','Metrics; scoring protocol; M01-M23','S12;S32;S34;L15;L19'),
('RV15','MAJOR','De centrale these mist een praktische falsificatiegrens','Een niet-significant verschil is niet automatisch tegenbewijs. H1 zegt slechts verhoogt, zonder minimaal relevant effect. H2 combineert winst en kosten zonder beslisregel. Daardoor kan elk klein voordeel worden gered als ondersteuning.','Leg estimands, vooraf te bepalen relevantie- en non-inferioriteitsmarges, onzekerheid en conditionele falsificatie vast. Onderscheid tegeneffect, verwaarloosbaar effect en onvoldoende informatie.','geaccepteerd','Getalsdrempels zonder belanghebbenden of pilot verzinnen zou even onjuist zijn; de preregistratie krijgt een expliciete startvoorwaarde.','Evaluatie; pre-evaluation research state','L03;P02'),
('RV16','CRITICAL','BAG-fragment draagt geen Stelselbrede claim','Er is niet eens een gevalideerd gekoppeld fragment met concrete definities en records, laat staan een vergelijking van meerdere registraties. Institutionele context is geen representatieve empirische casus.','Begrens conclusies tot ontwerp voor de context van het Stelsel; voeg een stage-gate toe die meerregistratieclaims blokkeert tot minimaal twee onafhankelijk beheerde registraties inhoudelijk en juridisch zijn onderbouwd.','geaccepteerd','Representativiteit kan niet redactioneel worden gerepareerd; dit blijft open empirisch werk.','Casus; conclusie; externe validiteit','S49;S25'),
('RV17','MINOR','Nederlandse standaardstatus is overwegend correct maar te indirect geciteerd','De gecontroleerde lijstpagina’s bevestigen NL-SBB 1.0 pas-toe-of-leg-uit, MIM 1.2 aanbevolen, DCAT-AP-NL 3.0 in behandeling en OpenAPI lijstversie 3.0. Specificatieversie, procedurestatus en verplicht toepassingsgebied moeten afzonderlijk citeerbaar blijven.','Voeg een compacte status-/scopetabel met directe lijstbronnen toe; neem geen algemene wettelijke plicht of effectclaim over uit wervende bronbeschrijvingen.','geaccepteerd','Er is geen reden een onjuistheid te verzinnen. Wel zijn procedurepagina’s veranderlijk en deels intern niet volledig bijgewerkt.','Nederlandse overheidscontext; standards matrix; broncontrole','S13;S14;S16;S19;S22'),
('RV18','MAJOR','Epistemische annotatie mengt nog steeds verschillende dimensies','Geregistreerd-zonder-afleiding staat naast deterministisch en AI. Ingevoerde waarden kunnen elders afgeleid zijn; AI is een techniekklasse, geen kansmodel. Authenticiteit is niet hetzelfde als waarschijnlijkheid of adjudiceerde waarheid.','Maak registratiehandeling, productiemethode, onzekerheidsmodel, gezagsgrond en bewijsstatus onafhankelijke velden. Registreer onbekend en betwist zonder opwaardering.','geaccepteerd','Een veld dat AI heet maakt probabilistische zekerheid niet meetbaar; de combinatie blijft eigen onderzoeksprofiel.','R23; metamodel; DP9; experiment E2','S33;L16'),
('RV19','MAJOR','Metadata introduceren eigen beveiligings- en vertrouwensproblemen','De evaluatie bespreekt niet systematisch misleidende provenance, ontoegankelijke bronnen, ingetrokken toegang, kwaadaardige context of uitlekken van informatie via identifiers en afleidingspaden. Dit zijn relevante aanvalsscenario’s, geen hier aangetoonde incidenten.','Voeg negatieve scenario’s en een toegangsfactor toe; scheid inhoudelijke bronclaims van vertrouwde instructies voor machineconsumenten. Toets onthouding bij ontoegankelijke context.','geaccepteerd','Een compleet securityframework is buiten scope; negeren van deze effectmoderatoren is niet verdedigbaar.','Threats to validity; governance; experiment E2/E4','S21;S33;L11'),
('RV20','MAJOR','Centrale semantisering kan pluraliteit en beheerbaarheid schaden','Een centrale beschrijving kan één interpretatie institutioneel bevoordelen, legitieme verschillen uitwissen en wijzigingen tot knelpunten maken. Een federatieve graaf kan op zijn beurt afhankelijkheids- en beschikbaarheidsproblemen toevoegen. Het ontwerp kan slechter zijn dan lokale contracten.','Maak centralisatie onafhankelijk van semantische explicitering, behoud betwiste mappings en vergelijk beheerinspanning, wijzigingslatency en lokale autonomie.','geaccepteerd','Dit zijn rivaliserende ontwerpverklaringen die negatief moeten kunnen uitpakken voor de gekozen architectuur.','Discussie; alternatiefanalyse; evaluatiekosten','L07;L12;S27'),
('RV21','MINOR','Geen fictieve prototype-uitkomsten aangetroffen','De paper scheidt toekomstige tests en bestaande bronbevindingen overwegend zorgvuldig. Het ontbreken van empirische resultaten is een inhoudelijke beperking, geen bewijs van misleiding.','Behoud die scheiding; vervang formuleringen die alleen administratieve dekking suggereren als bewijs door termen documentcontrole en ontwerpvoorstel.','geaccepteerd','Een kritische review moet ook vaststellen welke gevreesde fout niet is gevonden.','Onderzoeksstatus; audit; conclusie','L01;L03'),
('RV22','MAJOR','Broncontrole is nog geen clausule- of interpretatieaudit','De oorspronkelijke audit controleert sleutels en URL-herkomst. Dat bevestigt geen entailment, actualiteit of volledige dekking. ISO/NEN en verschillende artikelen blijven beperkt toegankelijk; sommige succesvolle HTTP-responses zijn slechts redirect- of scriptschermen.','Maak een claimniveau-bronaudit met access-status, geverifieerde passage, interpretatie, versie/scope en expliciete unresolved-vlag.','geaccepteerd','HTTP 200, bestaande DOI en citaatsleutel zijn geen inhoudelijk bewijs.','source-audit.csv; source-audit.md; claims-register','S01;S03;S08;S17;L03;L09'),
('RV23','MAJOR','Prototype-eigenschappen blijven volledig onbekend','De paper inventariseert alleen de afwezigheid van implementatiegegevens in deze repository. Dat is correct, maar een reviewer kan geen uitvoerbaarheid beoordelen.','Leg een lijst benodigde prototype-evidence vast en koppel iedere eigenschap aan een geplande test; laat alle statusvelden op niet beoordeeld.','geaccepteerd','Een echte inventarisatie kan zonder artefact niet worden uitgevoerd. Het open punt blijft zichtbaar in de response matrix.','Prototype; pre-evaluation research state','R01;R23'),
('RV24','EDITORIAL','De standaardcatalogus verdringt de argumentatie','De lange matrix en herhaalde disclaimers maken het 44-paginamanuscript eerder een dossier dan een gerichte paper. Er is veel herhaling tussen theorie, analyse en principes.','Verplaats de complete cross-standard tabel naar een appendix; laat in de hoofdtekst conflicten, kandidaatmappings en alternatiefselectie centraal staan.','geaccepteerd','De uitgebreide dekking blijft reviewbaar; geen belangrijke scopegrens verwijderen om de paper korter te laten lijken.','Cross-standard analysis; appendix',''),
('RV25','MAJOR','Traceability is administratief volledig maar semantisch dun','Een rij met Sxx→Rxx→DPx→Cx→Mx bewijst niet dat de bron de requirement draagt. Veel requirements verbinden meerdere onafhankelijk te toetsen beweringen.','Behoud IDs maar voeg een derivation-register toe met bronlocatie, inference warrant, alternatief, tegenbewijs en experiment. Toon deze inferenties ook in de paper.','geaccepteerd','Dit versterkt de controleerbaarheid zonder een niet-uitgevoerde inhoudelijke validatie te claimen.','Traceability appendix; derivation-register.csv','S08;L04'),
('RV26','MINOR','Een gekozen referentieversie is niet noodzakelijk de nieuwste versie','De paper is terecht versiegebonden. Actualiteitscontrole moet bevestigen wat op de gekozen pagina staat, niet automatisch overal de nieuwste release gebruiken. NL GOV CloudEvents vermeldt versie 1.1 maar heeft een linklabel 1.0; Digikoppeling gebruikt een redirectpagina.','Pin relevante publicaties; registreer pagina-inconsistenties en onvolledige toegang. Noem geselecteerde baselineversies en claim geen volledige release-monitoring.','geaccepteerd','Het is methodisch beter onzekerheid te registreren dan tegenstrijdige metadata stilzwijgend glad te strijken.','Broncontrole; bibliografie; versiebeleid','S20;S22;S37')]
cols=['reviewer_id','severity','reviewer_comment','beoordeling','voorgestelde_wijziging','besluit','rationale','gewijzigde_papersectie','bron_ids','uitvoeringsstatus']
data=[]
for i,se,title,judgement,change,decision,rationale,section,sources in findings:
 data.append(dict(zip(cols,[i,se,title,judgement,change,decision,rationale,section,sources,'Voorgesteld; review voltooid vóór revisie'])))
(ROOT/'review/findings.json').write_text(json.dumps(data,ensure_ascii=False,indent=2))
review='''# Kritische peer review — ingediende versie

**Advies: REJECT als afgeronde DSR-studie; MAJOR REVISION als pre-evaluation design proposal.** De brede these is niet bewezen. Het voorstel kan wetenschappelijk relevant worden, maar corpusdekking, een herkenbaar causaal mechanisme, een sterke eenvoudigere comparator en daadwerkelijke evaluatie ontbreken nog.

Dit rapport is voltooid vóór wijziging van het manuscript. De beoordeelde versie staat in `review/baseline/submitted-manuscript.zip` met SHA-256-manifest. De herbeoordeling is kritisch en heeft een afzonderlijke broncontrole, maar is verricht door dezelfde AI-assistent die het manuscript opstelde. Zij is daarom geen organisatorisch onafhankelijke externe peer review en evenmin een oordeel van een echt tijdschrift. Een nieuwe redeneringshouding verwijdert die afhankelijkheid niet.

## Samenvatting en sterke punten

De paper brengt betekenis, identiteit, tijd, gezag, provenance en publicatie in één ontwerpvoorstel bijeen. Het onderscheid tussen bronbevinding, ontwerpafleiding en toekomstige evaluatie is zorgvuldig. OntoUML wordt niet als Nederlandse standaard gepresenteerd. Herkomst wordt niet gelijkgesteld aan waarheid. De corpusbeperkingen en ontbrekende prototype-evaluatie worden openlijk benoemd. Deze zorgvuldigheid maakt het voorstel inspecteerbaar, maar vervangt geen onderzoeksbijdrage.

De zwakste schakel is niet een ontbrekende standaard, maar de stap van een geselecteerd pakket afspraken naar noodzakelijke en effectieve architectuur. De huidige paper is verenigbaar met de alternatieve verklaring dat dezelfde winst met een goed beheerd conventioneel metadataregister en dezelfde reviewinspanning ontstaat. De architectuur kan bovendien door onderhoudslast, foutieve mappings en institutionele centralisatie slechter presteren.

## Belangrijkste primaire tegenbronnen

- [Wang et al., SMDM, 2009](https://www.vldb.org/pvldb/vol2/vldb09-1011.pdf): directe voorganger van semantisch verrijkte masterdata. De demonstratie bewijst niets over dit Nederlandse ontwerp.
- [OMG DPROD, 1.0 Beta 1](https://www.omg.org/spec/DPROD/1.0/Beta1/PDF): bestaande productontologie met eigenaar, doel, lifecycle en gekoppelde datasets/diensten. Beta-status; geen Nederlandse verplichting of bewezen casusvoordeel.
- [Gualo et al., 2023](https://journals.sagepub.com/doi/10.15388/23-INFOR534): masterdatakwaliteitsmodel met standaardgebaseerde eigenschappen en metingen. Relevante voorganger, geen validatie van de gehele SMDP-keten.
- [SKOS §3.5.1](https://www.w3.org/TR/skos-reference/#notes): hetzelfde resource als SKOS-concept en OWL-klasse is toegestaan. Een verplichte scheiding in de paper is eigen profielbeleid.
- [MIM 1.2 §1.6](https://docs.geostandaarden.nl/mim/def-st-mim-20240613/): hanteert zelf een specifieke formulering van begrip en maakt conceptual/logical modelling expliciet. De paper moet verschil in woordgebruik analyseren in plaats van harmonisatie te veronderstellen.

De zoekactie is een gerichte tegencontrole, geen systematische review of bewijs dat alle antecedenten zijn gevonden. Zoekstrings en beperkte selectie staan in `review/search-log.md`.

## Volledige bevindingen
'''
for r in data:
 review+=f"\n### {r['reviewer_id']} — {r['severity']} — {r['reviewer_comment']}\n\n{r['beoordeling']}\n\n**Vereiste reactie:** {r['voorgestelde_wijziging']}\n\n**Revisiegrens:** {r['rationale']}\n"
review+='''
## Dekking van de twintig gevraagde beoordelingsvragen

| Vraag | Oordeel | Bevindingen |
|---|---|---|
| 1 Research gap | Niet aangetoond; directe antecedenten ontbreken | RV01 |
| 2 Meer dan standaardenintegratie | Nog geen gevalideerde meerwaarde; routine engineering blijft mogelijk | RV02, RV07 |
| 3 Definitie SMDP | Te weinig onderscheidende toelatingscriteria | RV03 |
| 4 Master/reference/metadata/product | Typegrenzen redelijk; gebruiksrollen onvoldoende uitgewerkt | RV04 |
| 5 Gebruik kernstandaarden | Scopes grotendeels correct; SKOS/MIM-nuances en mappings ontbreken | RV05, RV06, RV10 |
| 6 Redundantie | Ja, functioneel mogelijk; geen bewijs dat alles nodig is | RV07 |
| 7 OntoUML | Niet noodzakelijk; terecht optioneel, keuze moet toetsbaar | RV08 |
| 8 Eenvoudiger ontwerp | Plausibel alternatief dat niet serieus is uitgesloten | RV07, RV13 |
| 9 Abstractieniveaus | In proza onderscheiden, formele typering nog onvolledig | RV05, RV09 |
| 10 Normatief/descriptief | Benoemd, maar inferentiesprong bij MOET onvoldoende uitgewerkt | RV06, RV12 |
| 11 Nederlandse status | Gecontroleerde kernstatussen kloppen; bronkoppeling en inconsistenties expliciteren | RV17, RV26 |
| 12 Onbewezen causaliteit | Effecten meestal als hypothese; onderliggende interventie niet geïdentificeerd | RV13, RV15, RV21 |
| 13 Toekomst als resultaat | Geen fictieve prototype-uitkomsten aangetroffen | RV21 |
| 14 DSR | Geldige voorgenomen methode; geen afgeronde cyclus | RV11 |
| 15 Afleiding principes | Rationale aanwezig; geen bewijs van noodzakelijkheid/optimaliteit | RV12, RV25 |
| 16 Metrics | Deels meetbaar, maar constructen/noemers/criteria nog onvoldoende | RV14, RV15 |
| 17 Representativiteit | Onvoldoende voor conclusies over het Stelsel | RV16 |
| 18 Ontbrekende validity threats | Metadata-misleiding, reviewerafhankelijkheid, toegang, causale vertekening | RV19, RV20 |
| 19 Tegenargumenten | Centralisatie, pluraliteit, kosten en eenvoudigere representaties onvoldoende gewogen | RV07, RV20 |
| 20 Waarschijnlijke afwijzing | Nieuwheid, bijdrage, evaluatie, formalisme en casusbewijs | RV01, RV02, RV09, RV11, RV16 |

## Reviewerbesluit en acceptatievoorwaarden

De paper zou in een reguliere empirical/design-science research track waarschijnlijk worden afgewezen wegens onvoldoende gevalideerde bijdrage en onvoldoende vergelijking met bestaand werk. In een research-in-progress- of proposaltrack is herbeoordeling verdedigbaar nadat de gap is versmald, minimale alternatieven serieus zijn genomen, de formele contextbinding is uitgewerkt en falsificatie vooraf is gespecificeerd. De volledige lijst standaarden is daarvoor geen acceptatiecriterium.

Bronnen actualiseren en de tekst herschrijven kunnen drie open punten niet oplossen: externe wetenschappelijke nieuwheidsbeoordeling, een juridisch en inhoudelijk onderbouwde meerregistratiecasus en empirische evaluatie van het daadwerkelijke prototype. Deze blijven expliciete voorwaarden voor latere sterkere claims. Het gewenste onderzoek is falsifieerbaar als een gelijkwaardig eenvoudiger alternatief, negatieve effecten van semantisering of disproportionele beheerkosten de centrale ontwerpstelling kunnen doen vervallen.
'''
(ROOT/'peer-review.md').write_text(review)
# Record completion and verify the reviewed manuscript is still exactly the baseline.
manifest=json.loads((ROOT/'review/baseline/manifest.json').read_text())
for p,sha in manifest['files'].items():assert hashlib.sha256((ROOT/p).read_bytes()).hexdigest()==sha,p
(ROOT/'review/review-completed.json').write_text(json.dumps({'review_sha256':hashlib.sha256((ROOT/'peer-review.md').read_bytes()).hexdigest(),'baseline_unchanged_at_review_completion':True,'finding_count':len(data)},indent=2))
# Response matrix is written only after the complete review.
with (ROOT/'reviewer-response-matrix.csv').open('w',encoding='utf-8-sig',newline='') as f:
 w=csv.DictWriter(f,fieldnames=cols);w.writeheader();w.writerows(data)
print('Full review completed with unchanged manuscript:',len(data),'findings; response matrix written afterwards.')
